### ISSUE TITLE
`go get` gives error on fresh Ubuntu 14.04

### ISSUE THREAD

**Issue by amingilani** [Stephen304/bitcannon#24]
I get this error.

```bash
root@ubuntu:~/sandbox/bitcannon/api# go get
go install: no install location for directory /root/sandbox/bitcannon/api outside GOPATH
```
I have these:
- A fresh Ubuntu 14.04
- `go version` is `go1.2.1 linux/amd64`
- `$GOPATH` resolves to `/root/.go`
- `$PATH` resolves to `/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/root/.go/bin:/root/.go/bin`

**Comment by Stephen304** [comment]
This probably has to do with your go setup. Try building it and wait for it to complain about dependencies, then try to go get <url> those dependencies explicitly.

Alternatively, you can download the pre built package.

**Comment by Stephen304** [comment]
Ahah! I think I figured it out. Go get is (I think) supposed to automatically fetch all the dependencies, but it doesn't cooperate sometimes. Try to build it and when it complains about a missing package, use `go get <url>`

**Comment by amingilani** [comment]
@Stephen304, I've spent all day banging away at this. Built the system up from scratch again but no cigar.

**Comment by Stephen304** [comment]
What does it say when you try `go get <url>` for the missing dependency? Plain `go get` doesn't work I don't think.

**Comment by amingilani** [comment]
Okay, here's what I did and now I've managed to build it for the first time. Please explain this. I didn't find this process documented anywhere so I'll contribute it as soon as I get my instance running.

```bash
root@ubuntu:~/sandbox/bitcannon/api# go get -u github.com/jteeuwen/go-bindata/...
root@ubuntu:~/sandbox/bitcannon/api# mv ../web .
root@ubuntu:~/sandbox/bitcannon/api# make build
root@ubuntu:~/sandbox/bitcannon/api# cp config.example.json config.json
root@punkin:~/bitcannon/api# make build
rm -rf build
mkdir build
go-bindata -nocompress=true web/...
cp config.json build/
go build -o build/bitcannon
```

To summarize, I had to move the `web` directory into the `api` directory and found a `config.json`. 

Could you please tell me if what I did was right? And what does `config.json` do btw? Does it contain the list of sites bitcannon rips? Can I change the configuration on the fly, or must I recompile every time I need to add a site?

**Comment by Stephen304** [comment]
Sorry about the confusion. That's basically the right idea. You build web using grunt and copy the dist folder to api and rename it web. The Makefile in the main project folder does this for you, but it's not documented because I've been adding a lot recently due to the publicity in an attempt to make the final distributions as complete as possible.

The purpose of the config.json is to allow adjusting parameters on the fly, though some of them havent been implimented yet.

Another reason I have been lagging behind on documenting the build process is because, due to the complaints about mongo, I am trying to rewrite bitcannon to use an embedded database, so a lot of the process will change again.

If you have it working now, you can close this issue. The makefile in the main folder should help you. `make build` will do the trick, as long as you have the dependencies for web (nodejs, grunt, bower, all that jazz)

**Comment by amingilani** [comment]
Perfect, thanks! Just remember to give me a nudge when you think the project is stable enough to run in production. I would love to host my own cannon for personal use, and I could help with setting up and documentation too!
