### ISSUE TITLE
Don't use arrays for torrent meta

### ISSUE THREAD

**Issue by Stephen304** [Stephen304/bitcannon#32]
Since I don't plan to merge together duplicate torrents in favor of just skipping duplicates, this will make it much easier to build an algorithm to .Distinct() the categories and fix the browse page's slowness.

**Comment by skinnx86** [comment]
I wonder if skipping duplicates completely is good practice.  I selected two magnet links that had identical names but when both where opened in qbittorrent it merged the trackers instead of the popping up a notification saying "not added as it was a duplicate".  I believe this happens when I use two magnet links from seperate sites useing different trackers for the same file.  This help me speed up my download.  Maybe there is someway you can merge the trackers?  Or perhaps I'm barking up the wrong tree here.... TIA and great project btw, loving it

**Comment by Stephen304** [comment]
BitCannon actually doesn't tack on trackers to the magnet links. I forgot about this and I will definitely add it in the next release.

What I've actually done is a little cheat to not have to deal with storing trackers:
Since there are only a few trackers, I don't store trackers for every torrent, the config file just has a list of open trackers and I plan on just scraping them all for every torrent and hope that at least 1 tracker has the torrent. I did forget to add these trackers to the magnet link, though, so I'll make sure to do that so torrents won't download too slow.

**Comment by skinnx86** [comment]
Many Thanks.  I have seen many a post abouot you adding tracking scrapping, I take it this will be another point to add to the list then.
